# Generated by Django 5.1.2 on 2024-10-19 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyweathersummary',
            old_name='avg_temperature',
            new_name='avg_temp',
        ),
        migrations.RenameField(
            model_name='dailyweathersummary',
            old_name='max_temperature',
            new_name='max_temp',
        ),
        migrations.RenameField(
            model_name='dailyweathersummary',
            old_name='min_temperature',
            new_name='min_temp',
        ),
    ]
