# Generated by Django 5.1.2 on 2024-10-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_rename_avg_temperature_dailyweathersummary_avg_temp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyweathersummary',
            name='city',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='city',
        ),
        migrations.AddField(
            model_name='dailyweathersummary',
            name='avg_humidity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dailyweathersummary',
            name='avg_wind_speed',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dailyweathersummary',
            name='avg_temp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dailyweathersummary',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='dailyweathersummary',
            name='dominant_condition',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dailyweathersummary',
            name='max_temp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dailyweathersummary',
            name='min_temp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='feels_like',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='humidity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='main_condition',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='temperature',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='wind_speed',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('daily_weather', models.ManyToManyField(to='weather_app.dailyweathersummary')),
                ('weather', models.ManyToManyField(to='weather_app.weatherdata')),
            ],
        ),
    ]
